<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <Version>1.2.1.0</Version>
		<Authors>LanFengVVV</Authors>
		<Description>MBM.ModLoader mod for Monster Black Market — Adds status icons for pregnancy counts 4 and 5, and allows setting the upper limit on the Max Concurrent Fetuses. This mod is specifically designed for ComplexBreeding's larger Max Concurrent Fetuses.</Description>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<MBM>..\..\..\MBM.ModLoader For v2.1.2.0\Monster_Black_Market_v2.1.2.0 - MBM.ModLoader</MBM>
  </PropertyGroup>

	<ItemGroup>
		<AssemblyMetadata Include="ModPortal" Value="https://f95zone.to/threads/monster-black-market-lanfengvvvs-mods.302098/#post-20649932" />
		<AssemblyMetadata Include="Dependencies" Value="" />
	</ItemGroup>

  <ItemGroup>
    <None Remove="Sprites\slaveui_icon_fetus_4.png" />
    <None Remove="Sprites\slaveui_icon_fetus_5.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sprites\slaveui_icon_fetus_4.png">
      <LogicalName>slaveui_icon_fetus_4.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Sprites\slaveui_icon_fetus_5.png">
      <LogicalName>slaveui_icon_fetus_5.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(MBM)\MBM.ModLoader\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(MBM)\MonsterBlackMarket_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MBM.ModLoader">
      <HintPath>$(MBM)\MBM.ModLoader\MBM.ModLoader.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="spine-unity">
      <HintPath>$(MBM)\MonsterBlackMarket_Data\Managed\spine-unity.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(MBM)\MonsterBlackMarket_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MBM)\MonsterBlackMarket_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(MBM)\MonsterBlackMarket_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(MBM)\MonsterBlackMarket_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Strings.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<Compile Update="Properties\Strings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Strings.resx</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Properties\Strings.zh-CN.resx">
			<DependentUpon>Strings.resx</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Strings.ru.resx">
			<DependentUpon>Strings.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>

</Project>